//! Raw, unsafe bindings to `libneedle` — the Cactus Needle 3 on-device
//! inference engine. Generated by bindgen from `needle.h`; see `build.rs` for
//! artifact provenance and resolution order. The safe wrapper is
//! `forge_needle::ffi_backend::FfiBackend` (feature `ffi`).
//!
//! # Contract (verified 2026-09-23 against `macos-arm64/libneedle.a`,
//! sha256 `60cc14f1a2eda8da72b75f8f228fb72cadc2850b38702370f43e9660b74e951a`)
//!
//! Everything here operates on **one process-global, non-thread-safe model**.
//! Callers must serialise every call — `forge-needle`'s engine does this by
//! owning the backend on a single dedicated thread — and only one live
//! binding may exist per process.
//!
//! Call order and return conventions, each confirmed by running the real
//! library (not inferred from the header):
//!
//! * [`needle_load`] takes the `.cact` archive bytes and returns `0` on
//!   success, `-1` on failure (e.g. garbage bytes → `needle_last_error()` =
//!   "failed to load .cact model"). Loading the same archive twice is fine.
//!   The engine cannot *unload*: once weights are bound the process keeps
//!   them.
//! * [`needle_init`] installs the system-facts string and the tools JSON, and
//!   returns the tokenized static-prefix length (a *non-negative* count, e.g.
//!   63) or a negative error. Calling it again replaces the toolset, which is
//!   how one process serves several different tool surfaces.
//!   **It does not validate the tools JSON**: `"{not json"` and `"[]"` both
//!   return success, so callers must validate before calling.
//! * [`needle_complete`] returns the number of **tokens generated** (not
//!   bytes) or a negative error, and writes a NUL-terminated JSON envelope
//!   into `out`. It respects `out_capacity` (verified against a guard page)
//!   but **truncates silently** — a short buffer still returns success with
//!   invalid JSON in it, so callers must detect truncation themselves.
//! * [`needle_embed`] with a null `out` returns the embedding dimension
//!   (3072 for `needle3.cact`) without computing; with a real buffer it
//!   returns the number of floats written, which callers must check equals
//!   that dimension. A too-small capacity returns `-1` rather than
//!   overflowing. It needs [`needle_load`] but not [`needle_init`], and its
//!   result is independent of conversation state. Vectors come out
//!   L2-normalised.
//! * [`needle_reset`] clears the conversation, keeping the loaded weights and
//!   toolset.
//! * [`needle_last_error`] returns a runtime-owned C string that is only
//!   valid until the next API call — copy it out immediately. It points at an
//!   empty string (not null) when nothing has failed.

#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
